# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('Qt5Agg')

class design(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(698, 479)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")

        self.figure = plt.figure()
        self.canvas = FigureCanvas(self.figure)
        self.canvas.setObjectName("canvas")
        self.gridLayout.addWidget(self.canvas, 1, 1, 1, 1)

        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.slicesSlider = QtWidgets.QSlider(Form)
        self.slicesSlider.setOrientation(QtCore.Qt.Horizontal)
        self.slicesSlider.setObjectName("slicesSlider")
        self.gridLayout.addWidget(self.slicesSlider, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.loadButton = QtWidgets.QPushButton(Form)
        self.loadButton.setObjectName("loadButton")
        self.gridLayout.addWidget(self.loadButton, 0, 1, 1, 1)
        self.tresholdSlider = QtWidgets.QSlider(Form)
        self.tresholdSlider.setOrientation(QtCore.Qt.Horizontal)
        self.tresholdSlider.setObjectName("tresholdSlider")
        self.gridLayout.addWidget(self.tresholdSlider, 3, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Slices"))
        self.label_2.setText(_translate("Form", "Treshold"))
        self.loadButton.setText(_translate("Form", "Load"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = design()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
